spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

grpc:
  server:
    port: 9091

# actuator
management:
  server:
    port: 8081
